export const Strings = {
  common: {
    loading: 'Loading...',
    refresh: 'Refresh',
    checkStatus: 'Check Status',
    error: 'Error',
    success: 'Success',
    cancel: 'Cancel',
    ok: 'OK',
  },
  home: {
    headerSubtitle: 'Accept payments on the go',
    walletBalance: 'Wallet Balance',
    yourTerminals: 'Your Terminals',
    recentTransactions: 'Recent Transactions',
    createPayment: 'Create Payment Order',
    noTerminals: 'No terminals assigned yet',
    noTerminalsSub: 'Contact your admin to request a terminal',
    noTransactions: 'No transactions yet',
    waitingAssignment: 'Waiting for Assignment',
    waitingSubtitle: 'This device has been registered. Please contact your administrator to assign this device to your account.',
    stillWaiting: 'Still waiting for assignment',
  },
  login: {
    subtitle: 'Log in to your terminal',
    email: 'Email',
    password: 'Password',
    loginButton: 'Login',
    loginSuccess: 'Login successful',
    loginFailed: 'Login failed',
    fillFields: 'Please fill in all fields',
  },
  history: {
    title: 'Transaction History',
    subtitle: 'View and manage your terminal sales',
    empty: 'No transactions found',
    posSale: 'POS Sale',
  },
  settings: {
    title: 'Settings',
    profile: 'Profile',
    setPin: 'Set Operator PIN',
    logout: 'Logout',
    pinModalTitle: 'Set Operator PIN',
    pinModalSubtitle: 'Enter a 4-digit PIN for quick terminal access.',
    savePin: 'Save PIN',
    pinLengthError: 'PIN must be 4 digits',
    pinSuccess: 'PIN set successfully',
    pinFailed: 'Failed to set PIN',
  },
  pinLock: {
    title: 'Terminal Locked',
    subtitle: 'Enter operator PIN to continue',
    invalidPin: 'Invalid PIN',
    logout: 'LOGOUT',
  },
  transaction: {
    amount: 'Amount',
    description: 'Description',
    status: 'Status',
    date: 'Date',
    paymentMethods: 'Payment Methods',
    t0Settlement: 'T0 Settlement',
    completePayment: 'Complete Payment',
    paidSuccessfully: 'PAID SUCCESSFULLY',
    finish: 'Finish',
    completed: 'COMPLETED',
    done: 'Done',
    cancel: 'Cancel',
    selectOption: 'Select payment option',
    debitCreditCard: 'Debit or Credit Card',
    payWith: 'Pay with',
    qrCode: 'QR Code',
    quickAccess: 'Quick Access',
    mayaQr: 'Maya QR',
    qrph: 'QRPH',
    helpCenter: 'Help Center',
    charge: 'CHARGE',
  },
  guide: {
    activateTitle: 'Activate Real Payments',
    activateText: 'To transform this app into a real Maya terminal, configure your API keys in the backend environment.',
    step1: 'Get your Maya Business Manager keys',
    step2: 'Set MAYA_BUSINESS_API_KEY in Railway',
    step3: 'Set MAYA_BUSINESS_MODE to "live"',
    viewSetup: 'View Setup Documentation',
  }
};
